[package]
name = "ping_point"
version = "0.1.0"
edition = "2021"

[dependencies]
crossterm = "*"
tokio = { version = "*", features = ["full"] }
reqwest = "*"
clap = { version = "*", features = ["derive"] }
rand = "*"